name: Deploy socials
on:
  push:
    branches:
      - main
    paths:
      - apps/socials/**/*
  workflow_dispatch:
concurrency:
  group: deploy-socials
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/socials/Dockerfile
          tags: thatskyapplication-socials:latest
          load: true
          platforms: linux/amd64
          cache-from: type=gha,scope=deploy-thatskyapplication-socials
          cache-to: type=gha,mode=max,scope=deploy-thatskyapplication-socials
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Install docker-pussh
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -sSL https://raw.githubusercontent.com/psviderski/unregistry/v0.3.1/docker-pussh \
            -o ~/.docker/cli-plugins/docker-pussh
          chmod +x ~/.docker/cli-plugins/docker-pussh

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SERVER }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Push image to server
        run: docker pussh thatskyapplication-socials:latest ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}

      - name: Install Uncloud CLI
        run: |
          curl -fsS https://get.uncloud.run/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Deploy to Uncloud
        env:
          DATABASE_URL_CAELUS: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:5432/${{ secrets.POSTGRES_DB_CAELUS }}
          BETTER_STACK_TOKEN_SOCIALS: ${{ secrets.BETTER_STACK_TOKEN_SOCIALS }}
          BETTER_STACK_ENDPOINT_URL_SOCIALS: ${{ secrets.BETTER_STACK_ENDPOINT_URL_SOCIALS }}
          REDDIT_APPLICATION_ID: ${{ secrets.REDDIT_APPLICATION_ID }}
          REDDIT_APPLICATION_SECRET: ${{ secrets.REDDIT_APPLICATION_SECRET }}
        run: uc deploy --connect ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} --profile thatskyapplication-socials --recreate --yes
