name: Deploy commands
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm --filter @thatskyapplication/caelus... install

      - name: Build dependencies
        run: pnpm --filter @thatskyapplication/caelus^... run build

      - name: Deploy commands
        run: pnpm --filter @thatskyapplication/caelus run deploy-commands
        env:
          GITHUB_ACTIONS: true
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          SUPPORT_SERVER_GUILD_ID: ${{ vars.SUPPORT_SERVER_GUILD_ID }}
          TOP_GG_TOKEN: ${{ secrets.TOP_GG_TOKEN }}
